services:
  profiles_api:
    image: lapivan/innoprofilesapi:1.0.2
    ports:
      - "5242:8080"
    container_name: profiles_api
    depends_on:
      profiles_postgresql:
        condition: service_healthy
      profiles_mongodb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${PROFILES_DB_CONN}
      - ConnectionStrings__MongoLogging=${MONGO_LOGGING_CONN}
      - PasswordSettings__Key=${PASSWORD_SECRET_KEY}
  profiles_postgresql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: profiles_api_data_postgresql
    environment:
      - POSTGRES_DB=ProfilesApiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ProfilesApiDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - profiles_api_data:/var/lib/postgresql/data
  profiles_mongodb:
    image: mongo:8.0
    container_name: profiles_api_logs_mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - profiles_api_logs:/data/db
  services_api:
    image: lapivan/innoservicesapi:1.0.0
    ports:
      - "5243:8080"
    container_name: services_api
    depends_on:
      services_postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      profiles_api:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${SERVICES_DB_CONN}
      - ConnectionStrings__Redis=redis:6379
      - Services__ProfilesApiUrl=http://profiles_api:8080/

  services_postgresql:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    container_name: services_api_data_postgresql
    environment:
      - POSTGRES_DB=ServicesApiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ServicesApiDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - services_api_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: services_api_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  profiles_api_data:
  profiles_api_logs:
  services_api_data: